name: Issue Assignment

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign_assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to author
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const assignees = issue.assignees;
            if (assignees.length > 0) {
              console.log('이미 assignee가 지정되어 있습니다.');
              return;
            }
            const author = issue.user.login;
            const issue_number = issue.number;
            const { owner, repo } = context.repo;
            await github.rest.issues.addAssignees({
              owner: owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              assignees: [author]
            });
            